server:
  port: 8001

spring:
  application:
    name: cloud-payment-service #注册Eureka时不得使用下划线
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/sc2021?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.gwm.springcloud.entities    # 所有Entity别名类所在包