server:
  port: 80


eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
#spring:
#  application:
#    name: cloud_consumer_order
#  ####consul注册中心地址
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        #hostname: 127.0.0.1
spring:
  application:
    name: cloud_oder_service
#        service-name: ${spring.application.name}